name: CICD

on:
  push:
    branches: [feature/**/*, feature/*, main]
  pull_request:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: yarn install

      - name: Check Format
        run: yarn run nx format:check

      - name: Lint Workspace
        run: yarn run nx workspace-lint

      - name: Lint Apps
        run: yarn run affected:lint --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD  }}

      - name: Build Apps
        run: yarn run affected:build

      - name: No Outdated Packages
        if: github.ref == 'refs/heads/main'
        run: yarn run outdated

      - name: NX Report
        if: github.ref == 'refs/heads/main'
        run: yarn run nx report

      - name: Semantic release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: yarn run release

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2.1.37
        with:
          languages: 'typescript'
          external-repository-token: ${{ secrets.TOKEN_GITHUB }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2.1.37
